import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableOrder1739286260829 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
      await queryRunner.query(`
        create table orders(
          id int generated by default as identity primary key,
          name varchar(50),
          user_id int references users(id)
        );  
      `)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
      await queryRunner.query(`
        drop table order;  
      `)
    }

}
