import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1739262971712 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
      await queryRunner.query(`
        create table post (
          id int generated by default as identity primary key,
          title varchar(50) not null
        );  
      `)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
      await queryRunner.query(`
        drop table post
      `)
    }

}
