import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1739263086805 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
      await queryRunner.query(`
        create table comment (
          id int generated by default as identity primary key,
          content varchar(255),
          post_id int references post(id)
        );  
      `)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
      await queryRunner.query(`
        drop table comment;
      `)
    }

}
